model:
    arch: frrnA
data:
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /home/abrylov/data/
training:
    n_workers: 16
    train_iters: 45000
    batch_size: 3
    val_interval: 10000
    print_interval: 5000
    loss:
        name: bootstrapped_cross_entropy
        K: 32768
    optimizer:
        name: adam
        lr: 1.0e-3
        weight_decay: 0.0005
    lr_schedule:
        name: constant_lr
    resume: frrnB_cityscapes_best_model.pkl
    visdom: False